export const KAIRO_TRANSLATE_IDS = {
    ADDON_ACTIVE: "kairo.addon.active",
    ADDON_DEACTIVE: "kairo.addon.deactive",
    ADDON_CHANGE_VERSION: "kairo.addon.changeVersion",
    ADDON_LIST_TITLE: "kairo.addonList.title",
    ADDON_LIST_ACTIVE: "kairo.addonList.active",
    ADDON_LIST_INACTIVE: "kairo.addonList.inactive",
    ADDON_SETTING_LATEST_VERSION: "kairo.addonSetting.latestVersion",
    ADDON_SETTING_REQUIRED: "kairo.addonSetting.required",
    ADDON_SETTING_NONE_REQUIRED: "kairo.addonSetting.noneRequired",
    ADDON_SETTING_ACTIVE: "kairo.addonSetting.active",
    ADDON_SETTING_SELECTED: "kairo.addonSetting.selected",
    ADDON_SETTING_UNINSTALLED: "kairo.addonSetting.uninstalled",
    ADDON_SETTING_MISSING_REQUIRED: "kairo.addonSetting.missing.required",
    ADDON_SETTING_REGISTERED_ADDON_LIST: "kairo.addonSetting.registeredAddonList",
    ADDON_SETTING_SELECT_VERSION: "kairo.addonSetting.selectVersion",
    ADDON_SETTING_ACTIVATE: "kairo.addonSetting.activate",
    ADDON_SETTING_SUBMIT: "kairo.addonSetting.submit",
    ADDON_SETTING_REQUIRED_TITLE: "kairo.addonSetting.required.title",
    ADDON_SETTING_REQUIRED_ACTIVATION_BODY: "kairo.addonSetting.required.activation.body",
    ADDON_SETTING_REQUIRED_DEACTIVATION_BODY: "kairo.addonSetting.required.deactivation.body",
    ADDON_SETTING_REQUIRED_ACTIVE_CONFIRM: "kairo.addonSetting.required.active.confirm",
    ADDON_SETTING_REQUIRED_DEACTIVE_CONFIRM: "kairo.addonSetting.required.deactive.confirm",
    ADDON_SETTING_REQUIRED_CANCEL: "kairo.addonSetting.required.cancel",
    ERROR_FORM_TITLE: "kairo.errorForm.title",
    ERROR_FORM_HEADER: "kairo.errorForm.header",
    ERROR_FORM_FOOTER: "kairo.errorForm.footer"
}